// exampleMixin.js
export const ListasMixin = {
    data() {
      return {
        mixinMessage: "Hello from the mixin!",
         
        listaUFs: [ "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" ],
        especializacaoItems: [ 'Especialista', 'Mestre', 'Doutor(a)', 'Pós-Doutor(a)' ],
        generos: [ 'Homem', 'Mulher', 'Não-binário', 'Outro' ],
        instituicaoItems: [
          "Universidade Federal do Amapá (UNIFAP)",
          "Universidade Federal do Amazonas (UFAM)",
          "Universidade Federal de Rondônia (UNIR)",
          "Universidade Federal do Pará (UFPA)",
          "Universidade Federal de Roraima (UFRR)",
          "Universidade Federal do Tocantins (UFT)",
          "Universidade Federal da Bahia (UFBA)",
          "Universidade Federal do Ceará (UFC)",
          "Universidade Federal do Maranhão (UFMA)",
          "Universidade Federal de Paraíba (UFPB)",
          "Universidade Federal de Pernambuco (UFPE)",
          "Universidade Federal do Piauí (UFPI)",
          "Universidade Federal de Sergipe (UFS)",
          "Universidade Federal de Brasília (UNB)",
          "Universidade Federal de Goiás (UFG)",
          "Universidade Federal de Mato Grosso (UFMT)",
          "Universidade Federal de Mato Grosso do Sul (UFMS)",
          "Universidade Federal de Alfenas (UNIFAL-MG)",
          "Universidade Federal de Itajubá (UNIFEI)",
          "Universidade Federal de Juiz de Fora (UFJF)",
          "Universidade Federal de Lavras (UFLA)",
          "Universidade Federal de Minas Gerais (UFMG)",
          "Universidade Federal do Espírito Santo (UFES)",
          "Universidade Federal Fluminense (UFF)",
          "Universidade Federal de Ouro Preto (UFOP)",
          "Universidade Federal de São João del-Rei (UFSJ)",
          "Universidade Federal de Viçosa (UFV)",
          "Universidade Federal do Rio de Janeiro (UFRJ)",
          "Universidade Federal Rural do Rio de Janeiro (UFRRJ)",
          "Universidade de São Paulo (USP)",
          "Universidade Estadual Paulista 'Júlio de Mesquita Filho' (UNESP)",
          "Universidade Federal do Paraná (UFPR)",
          "Universidade Federal do Rio Grande do Sul (UFRGS)",
          "Universidade Federal de Santa Catarina (UFSC)",
          "Universidade Federal de Santa Maria (UFSM)"
        ],
        abordagensItems: [
          "Psicoterapia de Apoio (Psicodinâmica)",
          "Psicoterapia Psicodinâmica Relacional (Psicodinâmica)",
          "Psicoterapia Psicodinâmica Breve (Psicodinâmica)",
          "Psicoterapia Interpessoal (Psicanalítica)",
          "Psicologia Individual (Psicanalítica)",
          "Psicanálise Lacaniana (Psicanalítica)",
          "Psicanálise Junguiana (Psicanalítica)",
          "Psicanálise Clássica (Psicanalítica)",
          "Psicoterapia Focal (Psicodinâmica)",
          "Terapia Comportamental (Comportamental e Cognitiva)",
          "Terapia Cognitivo-Comportamental (TCC) (Comportamental e Cognitiva)",
          "Terapia Cognitiva (Comportamental e Cognitiva)",
          "Terapia Racional-Emotiva Comportamental (TREC) (Comportamental e Cognitiva)",
          "Análise do Comportamento Aplicada (ABA) (Comportamental e Cognitiva)",
          "Terapia Dialética Comportamental (DBT) (Comportamental e Cognitiva)",
          "Terapia de Aceitação e Compromisso (ACT) (Comportamental e Cognitiva)",
          "Terapia Centrada no Cliente (Humanista)",
          "Terapia Gestalt (Humanista)",
          "Logoterapia (Humanista)",
          "Análise Existencial (Humanista)",
          "Psicossíntese (Humanista)",
          "Terapia Fenomenológica (Humanista)",
          "Terapia Familiar Estrutural (Sistêmica e Familiar)",
          "Terapia Familiar Sistêmica (Sistêmica e Familiar)",
          "Terapia Estratégica (Sistêmica e Familiar)",
          "Terapia Narrativa (Sistêmica e Familiar)",
          "Terapia de Casal e Família Centrada nas Emoções (Sistêmica e Familiar)",
          "Terapia Familiar Funcional (Sistêmica e Familiar)",
          "Terapia Reichiana (Corporal e Somática)",
          "Análise Bioenergética (Corporal e Somática)",
          "Terapia Somática (Corporal e Somática)",
          "Core Energetics (Corporal e Somática)",
          "Terapia de Movimento e Dança (Corporal e Somática)",
          "Terapia Integrativa (Integrativa)",
          "Terapia Psicossomática (Integrativa)",
          "Psicoterapia Relacional Integrativa (Integrativa)",
          "Psicoterapia Integral (Integrativa)",
          "Mindfulness-Based Cognitive Therapy (MBCT) (Terceira Onda)",
          "Mindfulness-Based Stress Reduction (MBSR) (Terceira Onda)",
          "Psicologia Comunitária (Cultural e Social)",
          "Psicoterapia Transcultural (Cultural e Social)",
          "Psicoterapia Feminista (Cultural e Social)",
          "Psicoterapia LGBTQ+ Afirmativa (Cultural e Social)",
          "Terapia Colaborativa (Pós-moderna e Construtivista)",
          "Terapia Construtivista (Pós-moderna e Construtivista)",
          "Terapia Pós-modernista (Pós-moderna e Construtivista)",
          "Terapia de Grupo (Grupos)",
          "Terapia de Grupos de Encontro (Grupos)",
          "Terapia de Grupo Psicodinâmica (Grupos)",
          "Terapia de Grupo Cognitivo-Comportamental (Grupos)",
          "Terapia EMDR (Baseada em Evidências e Neurociências)",
          "Neurofeedback (Baseada em Evidências e Neurociências)",
          "Psicoterapia baseada em Neurociência (Baseada em Evidências e Neurociências)",
          "Hipnoterapia (Outras)",
          "Terapia Breve (Outras)",
          "Terapia de Crise (Outras)",
          "Psicoterapia Interpessoal (Outras)",
          "Terapia de Suporte (Outras)",
          "Psicoterapia Transpessoal (Outras)"
          ],
          profissoesItems: [ 
            "Administrador(a)",
            "Advogado(a)",
            "Analista de sistemas",
            "Analista financeiro(a)",
            "Arquiteto(a)",
            "Assistente social",
            "Bombeiro(a)",
            "Cabeleireiro(a)",
            "Contador(a)",
            "Costureiro(a)",
            "Cozinheiro(a)",
            "Dentista",
            "Designer gráfico(a)",
            "Economista",
            "Eletricista",
            "Engenheiro(a)",
            "Farmacêutico(a)",
            "Fisioterapeuta",
            "Garçom/Garçonete",
            "Jornalista",
            "Médico",
            "Médico veterinário",
            "Mecânico(a)",
            "Nutricionista",
            "Operador(a) de máquinas",
            "Pedagogo(a)",
            "Pedreiro(a)",
            "Policial",
            "Programador(a) de computadores",
            "Professor(a)",
            "Professor(a) de educação física",
            "Publicitário(a)",
            "Técnico(a) em enfermagem",
            "Técnico(a) em informática",
            "Técnico(a) em radiologia",
            "Técnico(a) em segurança do trabalho",
            "Outro"
          ],
          cirurgiasItems: [
            "Cardíaca",
            "Ortopédica",
            "Plástica",
            "Oncológica",
            "Neurológica",
            "Oftalmológica",
            "Bariátrica",
            "Torácica",
            "Vascular",
            "Ginecológica",
            "Urológica",
            "Gastrointestinal",
            "Otorrinolaringológica",
            "Maxilofacial",
            "Pediátrica",
            "Reprodutiva",
            "Endocrina",
            "Dermatológica",
            "Hepatobiliar",
            "Proctológica",
            "Transplantes",
            "Catarata",
            "Aneurisma",
            "Hérnia",
            "Laparoscópica",
            "Outra(s)"
        ],
        drogasItens:      [
          "Alucinógenos (cogumelos psilocibinos)",
          "Anfetaminas",
          "Ayahuasca",
          "Barbitúricos",
          "Benzodiazepínicos ",
          "Cannabis (maconha)",
          "Cocaína",
          "Crack",
          "DMT",
          "MDMA (Ecstasy)",
          "Estimulantes",
          "Esteroides anabolizantes",
          "Fenciclidina (PCP ou 'pó de anjo')",
          "GHB (ácido gama-hidroxibutírico)",
          "Inalantes (cola, aerossóis, etc)",
          "Ketamina",
          "Khat",
          "LSD",
          "Metanfetaminas",
          "Opioides (morfina, heroína e oxicodona)",
          "Salvia divinorum",
          "Solventes (como gasolina e thinner)",
          "Xarope de Codeína",
          "Nenhuma"
        ],
          
      };
    },
     
    created()           {
        // alert("Mixin's created hook called !!!!!!!");
    },
  };
  export default ListasMixin;
  